version: '3.4'

services:
  smsrapp:
    image: slogans-municipio-front
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5050:80
      - 5043:443
    restart: always
    volumes:
      - "./certs:/etc/nginx/certs"
